### ISSUE TITLE
Support for RVM custom location

### ISSUE THREAD

**Issue by lucasefe** [srushti/goldberg#79]
I have installed rvm into /usr/local/rvm, so the build process is not working. 
Reviewing the RVM class I saw a hardcoded value for the RVM path. I think this should be customizable. 

Thanks!

Lucas Florio

**Comment by lucasefe** [comment]
BTW, if I symlink my rvm folder to $HOME/.rvm, the build seems to work.

**Comment by srushti** [comment]
Good catch. We'll work on this immediately. None of us have system rvm installed and so it didn't occur to us to make this configurable.

**Comment by lucasefe** [comment]
I have something working on my fork. 

https://github.com/lucasefe/goldberg/blob/master/app/models/rvm.rb

Tell if this is good enough for you, so I will do a Pull Request. 

Cheers

**Comment by srushti** [comment]
Thanks, I've merged in the changes. I noticed one thing which I was curious about. The system script path didn't include the root directory ('usr/local/rvm/scripts/rvm'). Does that work fine for you? I've added a '/' to the beginning, and also expanded the tests to work with the system rvm as well.
Let me know if it works fine, and I'll close this ticket.

**Comment by lucasefe** [comment]
Cool! Regarding the path, let me tell you that I did not have a chance to test it, because I was still having problems starting up Goldberg with passenger 3.0.7 (there's a ticket for this too). So your correction is right. The / slash was needed. 

Thanks.
